Implementation of restrictions, validations and custom messages
CADELmx/GPD_BACKEND pull request #20
Opened 2024-07-11 09:07 UTC by coby111

## Overview
This PR introduces the following improvements and functionalities to the template service:

**Template creation:**
 - Updated the method to create templates (`create`).
 - Validation of foreign keys.
 - Exception handling with custom messages.

**List of templates:**
 - Updated the method to list all templates (`findAll`).
 - Exception handling with custom messages.

 **Template update:**
 - Update of the method to update templates (`update`).
 - Period validation.
 - Exception handling with custom messages.

 **Deletion of templates:**
 - Updated the method to remove templates (`remove`).
 - Exception handling with custom messages.

**Validation of IDs and foreign keys:**
 - Added method to validate existing template ID (`validateId`).
 - Added method to validate foreign keys (`validateAreaId`, `validateResponsibleId`, `validateRevisedById`).

**DTOs with validations:**
 - Updated `CreateTemplateDto` with validations and custom messages.
 - Updated `UpdateTemplateDto` with validations and custom messages.

## Changes

### Service

- **create**
- **findAll**
- **update**
- **remove**
- **validateId**
- **validateAreaId**
- **validateRevisedById**
- **validateResponsibleId**

### DTOs

- **CreateTemplateDto**
- **UpdateTemplateDto**

## How to test

1. **Template creation:**
 - Send a POST request to `/templates` with valid and invalid data to check validations and error messages.

2. **List of templates:**
 - Send a GET request to `/templates` to check listing and exception handling.

3. **Template update:**
 - Send a PATCH request to `/templates/:id` with valid and invalid data to check validations and error messages.

4. **Template removal:**
 - Send a DELETE request to `/templates/:id` to check for deletion and exception handling.

## Related Issues
- Closes #6 

Thank you for reviewing this pull request. I look forward to your feedback.

2024-07-11 15:44 UTC, DiegoSHS requested changes
Check the comments, just those changes and that's it

2024-07-11 15:44 UTC, DiegoSHS commented on src/models/template/create-template.dto.ts
> +import { IsInt, IsNotEmpty, IsString, Min } from 'class-validator';
Change the messages for responsibleId and revisedId, avoid yo use the word "id"

2024-07-11 15:44 UTC, DiegoSHS commented on src/models/template/update-template.dto.ts
> +import { IsInt, IsNotEmpty, IsOptional, IsString, Min } from 'class-validator';
Same for the UpdateDTO, avoid using the word "ID" for those fields

2024-07-12 16:42 UTC, DiegoSHS approved these changes
Reviewed again, good changes

2024-07-12 20:44 UTC, elisa242003 approved these changes
Correct, the changes are well applied, there are no problems

2024-07-12 21:26 UTC, merged