Hot Fix: inconsistency of changes since last merge conflicts resolution
CADELmx/GPD_BACKEND pull request #25
Opened 2024-07-14 21:21 UTC by DiegoSHS

## Overview
This pull request fixes some errors in the name of methods used in the subjects service.

### Details
These are the same changes, some of these were lost in the last merge conflicts resolution

2024-07-14 21:30 UTC, DiegoSHS reviewed
Auto check, done

2024-07-15 02:14 UTC, elisa242003 approved these changes
Approved, changes implemented correctly

2024-07-15 03:26 UTC, coby111 commented on src/subject/subject.controller.ts
delete method missing

2024-07-15 03:27 UTC, coby111 requested changes
Consider updates

2024-07-15 04:12 UTC, coby111 approved these changes
Changes approved, no comments, everything perfect <3

2024-07-15 04:12 UTC, merged